name: "🚀 Release: Plugin version"

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      arch:
        default: x86_64
        required: true
      platform:
        default: windows
        required: true
      profile:
        default: debug
        required: true

defaults:
  run:
    shell: bash

permissions:
  contents: write
  pull-requests: write

jobs:
  # # NOTE: This job exists just to allow defining default input values *once*,
  # # regardless of whether an input is set for the workflow's event type.
  # inputs:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 1

  #   outputs:
  #     platform: ${{ inputs.platform || '17' }}

  build-extension:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # strategy:
    #   fail-fast: false
    #   max-parallel: 2

    #   matrix:
    #     include:
    #       # - arch: universal
    #       #   platform: macos
    #       #   profile: debug

    #       # - arch: universal
    #       #   platform: macos
    #       #   profile: release

    #       - arch: x86_64
    #         platform: windows
    #         profile: debug

    #       # - arch: x86_64
    #       #   platform: windows
    #       #   storefront: unknown
    #       #   profile: release

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # ------------------------ Setup: Steamworks SDK ----------------------- #

      - run: rm godotsteam/sdk/.gitkeep

      - uses: actions/checkout@v4
        with:
          repository: ${{ secrets.STEAMWORKS_REPO }}
          ref: v1.61
          token: ${{ secrets.STEAMWORKS_PAT }}
          path: godotsteam/sdk

      # ------------------------- Compile: Extension ------------------------- #

      - uses: coffeebeats/godot-infra/compile-godot-extension@feat/compile/extension
        id: version
        with:
          extension-path: "."
          arch: ${{ inputs.arch }}
          platform: ${{inputs.platform }}
          profile: ${{inputs.profile }}

      # - uses: coffeebeats/godot-infra/.github/actions/setup-godot@v1
      #   with:
      #     version: ${{ steps.version.outputs.semantic }}

      # - name: Construct addon directory
      #   id: addon
      #   run: |
      #     mkdir ${{ runner.temp }}/addon

      #     # Set options to enable more extensive globbing.
      #     shopt -s extglob
      #     shopt -s globstar

      #     cp -r * ${{ runner.temp }}/addon

      #     # Remove development/project-related files.
      #     rm ${{ runner.temp }}/addon/project.godot
      #     rm ${{ runner.temp }}/addon/icon.*
      #     rm -rf ${{ runner.temp }}/addon/script_templates

      #     # Remove all nested addon dependencies.
      #     rm -rf ${{ runner.temp }}/addon/addons

      #     # Remove testing-related files.
      #     rm ${{ runner.temp }}/addon/**/*_test.gd

      #     # Add pruned directory into project as an addon
      #     SUBFOLDER="$(echo ${{ github.repository }} | sed -E 's/^${{ github.repository_owner }}\/godot-plugin-//')"
      #     mv ${{ runner.temp }}/addon "addons/$SUBFOLDER"

      #     # Reimport assets so *.import files are updated.
      #     godot --editor --headless --import --quit

      #     # Move the updated addon folder to the target path.
      #     mv "addons/$SUBFOLDER" ${{ runner.temp }}/addon

      #     echo "Addon files to publish:"
      #     ls -lsa ${{ runner.temp }}/addon

      # - name: Check out to target branch
      #   id: branch
      #   run: |
      #     TARGET_BRANCH="godot-v${{ steps.version.outputs.major-minor }}"
      #     BRANCHES=$(git ls-remote --heads origin $TARGET_BRANCH)

      #     if [[ -z "$BRANCHES" ]]; then
      #       git checkout -b $TARGET_BRANCH
      #     else
      #       git fetch origin +refs/heads/$TARGET_BRANCH:refs/heads/$TARGET_BRANCH
      #       git checkout $TARGET_BRANCH
      #     fi

      #     echo "target=$TARGET_BRANCH" >> $GITHUB_OUTPUT

      # - name: Push the latest changes to the target branch
      #   run: |
      #     # Set options to enable more extensive globbing.
      #     shopt -s extglob
      #     shopt -s globstar

      #     rm -rf * .@(!(.||git))

      #     # Remove submodules
      #     rm -rf .gitmodules .git/modules

      #     echo "Target addon workspace (before):"
      #     ls -lsa .

      #     cp -r ${{ runner.temp }}/addon/* .

      #     echo "Target addon workspace (after):"
      #     ls -lsa .

      #     if [[ -z "$(git status --porcelain)" ]]; then
      #       echo "Target branch is up-to-date; exiting without making changes."
      #       exit 0
      #     fi

      #     # See https://github.com/orgs/community/discussions/26560#discussioncomment-3531273
      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git config user.name "github-actions[bot]"

      #     git add --all .
      #     git commit -m "chore: updating ${{ github.repository }}@${{ steps.branch.outputs.target }} to ${{ github.sha }} (on behalf of '${{ github.triggering_actor }}')"

      #     git push origin ${{ steps.branch.outputs.target }}
